//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOBA.Assets {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FreeWp8Icons_White {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FreeWp8Icons_White() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOBA.Assets.FreeWp8Icons_White", typeof(FreeWp8Icons_White).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Abort {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Abort", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Abort_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Abort_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Add {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Add_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Apply {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Apply_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Apply_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Cancel {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Cancel_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Cancel_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Clear {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Clear_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Clear_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Close {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Close_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Close_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Delete {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Delete_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Erase {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Erase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Erase_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Erase_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Error {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Error_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Error_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Help {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Help_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Help_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Info {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Info_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Info_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_No {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_No", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_No_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_No_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_No_entry {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_No_entry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_No_entry_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_No_entry_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_OK {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_OK_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_OK_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Pause_button {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Pause_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Pause_button_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Pause_button_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Problem {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Problem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Problem_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Problem_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Question {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Question_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Question_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Refresh {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Refresh_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Remove {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Remove_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Remove_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Stop {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Stop_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Stop_button {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Stop_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Stop_button_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Stop_button_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Warning {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap FreeWp8IconsWhite_Warning_32 {
            get {
                object obj = ResourceManager.GetObject("FreeWp8IconsWhite_Warning_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
